# -*- coding: utf-8 -*-
"""Shafira_IDCAMP_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15mxE9am-J6iDYOvaF32gdqy49tjz_QPl

# Proyek Analisis Data: Nama dataset
- Nama: Shafira Faira Huwaida
- Email: shafirafaira.2019@student.uny.ac.id
- Id Dicoding: shaf_faira

## Menentukan Pertanyaan Bisnis

- pertanyaan 1
produk apa saja yang paling laku selama tahun 2017?

- pertanyaan 2
Pada bulan berapa order tertinggi selama tahun 2017?

- pertanyaan 3
Berapa jumlah customer loyal selama tahun 2017 dan 2018?

## Menyiapkan semua library yang dibutuhkan
"""

#!pip install streamlit
#!pip install folium

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import folium

st.header('🛍️ Dashboard Brasilia E-Commerce Dataset')

st.title("Distribution of Customers in Brazil")

# Load ke DataFrame
df = pd.read_csv("df.csv")

# Pastikan kolom waktu dalam format datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

# ============================
# Sidebar untuk filter tanggal
# ============================
st.sidebar.header("Filter Waktu")

min_date = df['order_purchase_timestamp'].min().date()
max_date = df['order_purchase_timestamp'].max().date()

start_date = st.sidebar.date_input("Tanggal Mulai", min_date)
end_date = st.sidebar.date_input("Tanggal Selesai", max_date)

df_filtered = df[(df['order_purchase_timestamp'].dt.date >= start_date) & 
                 (df['order_purchase_timestamp'].dt.date <= end_date)]

# ============================
# Pertanyaan 1: Produk paling laku selama tahun 2017?
# ============================
grouped = df_filtered.groupby('product_category_name')['price'].sum().reset_index()
grouped = grouped.sort_values(by='price', ascending=False)
top8 = grouped.head(8)
other = pd.DataFrame({'product_category_name': ['Other'], 'price': [grouped['price'].iloc[8:].sum()]})
pie_data = pd.concat([top8, other])

fig1, ax1 = plt.subplots(figsize=(8,8))
ax1.pie(pie_data['price'], labels=pie_data['product_category_name'], autopct='%1.1f%%', startangle=140)
ax1.set_title('Total Amount per Category (Top 8 + Other)')
st.pyplot(fig1)

# Tambahkan kesimpulan di Streamlit
st.subheader("Insight 1")
st.write("Produk paling laku selama tahun 2017 adalah kategory cama mesa banho."
         "Terlihat bahwa 8.2% penjualan selama 2017 berasal dari cama mesa banho.")

# ============================
# Pertanyaan 2: Pada bulan berapa order tertinggi selama tahun 2017?
# ============================
orders_per_month = df_filtered.groupby(df_filtered['order_purchase_timestamp'].dt.to_period('M')).size().reset_index(name='order_count')
orders_per_month['order_purchase_timestamp'] = orders_per_month['order_purchase_timestamp'].dt.to_timestamp()

if orders_per_month.empty:
    st.subheader("Insight 2")
    st.write("Data tidak tersedia untuk range waktu yang dipilih.")
else:
    # Buat grafik
    fig2, ax2 = plt.subplots(figsize=(10,5))
    ax2.plot(orders_per_month['order_purchase_timestamp'], orders_per_month['order_count'], marker='o')
    ax2.set_xlabel('Waktu (Bulan)')
    ax2.set_ylabel('Jumlah Order')
    ax2.set_title('Jumlah Order per Bulan')
    plt.xticks(rotation=45)
    st.pyplot(fig2)

# Tambahkan kesimpulan di Streamlit
st.subheader("Insight 2")
st.write("Pada tahun 2017, order terbanyak berada di bulan 11 (November)."
         "Terlihat dari puncak grafik tertinggi pada bulan November yang terdiri lebih dari 8000 order.")

# ============================
# Pertanyaan 3: Berapa jumlah customer loyal selama tahun 2017 dan 2018? 
# ============================
recency_df = df_filtered.groupby(['customer_id'], as_index=False)['order_purchase_timestamp'].max()
recency_df.columns = ['customer_id','LastPurchaseDate']
now = pd.Timestamp.now()
recency_df['Recency'] = (now - recency_df['LastPurchaseDate']).dt.days

resi_count = df_filtered.groupby('customer_id').size().reset_index(name='Frequency')

price_sum = df_filtered.groupby('customer_id', as_index=False)['price'].sum()
price_sum.columns = ['customer_id', 'Monetary']

rfm = recency_df.merge(resi_count, on='customer_id').merge(price_sum, on='customer_id')
rfm = rfm[rfm['Monetary'] != 0]
rfm['R'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])
rfm['F'] = pd.cut(rfm['Frequency'], bins=[0,5,10,15,rfm['Frequency'].max()], labels=[1,2,3,4])
rfm['M'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])
rfm['Score'] = rfm[['R','F','M']].sum(axis=1)

def categorize(score):
    if score >= 10: return 'Champions'
    elif score >= 7: return 'Loyal Customers'
    elif score >= 4: return 'Potential Loyalists / At Risk'
    else: return 'Hibernating / Lost'

rfm['Segment'] = rfm['Score'].apply(categorize)
segment_counts = rfm['Segment'].value_counts()

fig3, ax3 = plt.subplots(figsize=(8,6))
segment_counts.plot(kind='bar', color='skyblue', edgecolor='black', ax=ax3)
ax3.set_xlabel('Segment')
ax3.set_ylabel('Jumlah Pelanggan')
ax3.set_title('Distribusi Pelanggan per Segment RFM')
st.pyplot(fig3)

# Tambahkan kesimpulan di Streamlit
st.subheader("Insight 3")
st.write("Pada tahun 2017 customer terdiri dari kategori potential loyal/ at risk, hibernating/ lost, dan loyal customers."
         "Pada tahun 2018 customer terdiri dari kategori customer loyal customers, potential loyalist/at risk, dan champions."
         "Dari grafik, menunjukkan bahwa dari tahun 2017 ke tahun 2018 terdapat kenaikan/perbaikan kualitas, sehingga pada tahun 2018 tidak terdapat customer hibernating/lost.")

# Conclusion
st.markdown("**Conclusion:** "
            "- berdasarkan hasil rfm, customer bisa melakukan pembelian hingga nilai 6735, sedangkan rata-rata pembelian 120. hal tersebut menunjukkan bahwa penjualan masih bisa dioptimalkan dengan mengatur strategi yang tepat."
            "- berdasarkan hasil rfm, juga diperoleh informasi bahwa customer hibernating/lost sudah tidak ada pada tahun 2018. namun perlu diperhatikan bahwa, at risk masih tinggi sehingga diperlukan program yang mendukung untuk kedepannya."
            "- berdasarkan line chart jumlah order, diketahui bahwa orderan tahun 2017 ke 2018 cenderung naik. namun perlu menjadi perhatian bahwa akhir 2018 terjadi penurunan drastis, sehingga perlu diteliti lebih lanjut."
            )
